server:
  port: 80
spring:
  application:
    name: MI-GATEWAY-SERVER
  datasource:
    url: jdbc:mysql://cdb-bopgeseg.cd.tencentcdb.com:10054/gateway?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: weihanhan1005
  cloud:
    nacos:
      server-addr: 39.97.76.127
      discovery:
        group: MI-GROUP
  webflux:
    hiddenmethod:
      filter:
        enabled: false
  redis:
    cluster:
      nodes:
        - 81.70.197.232:6391
        - 81.70.197.232:6392
        - 81.70.197.232:6393
        - 81.70.197.232:6394
        - 81.70.197.232:6395
        - 81.70.197.232:6396
aliyun:
  captcha:
    region-id: cn-hangzhou
    access-key-id: LTAI4G6dh6WpfJXQXgHGzGi6
    access-key-secret: XmXumSWCQawqxiXWhEmcVJF3aNil2g
    app-key: FFFF0N000000000098E9
web:
  client:
    client-id: admin-web
    client-secret: 123456
    scope: server
    password-grant-type: password
    phone-verify-code-grant-type: verify_code
    social-grant-type: social_auth
