server:
  port: 80
spring:
  application:
    name: MI-GATEWAY-SERVER
  datasource:
    url: jdbc:mysql://cdb-bopgeseg.cd.tencentcdb.com:10054/gateway?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: weihanhan1005
  cloud:
    nacos:
      server-addr: 39.97.76.127
      discovery:
        group: MI-GROUP
