server:
  port: 1004
  tomcat:
    max-swallow-size: 100MB
spring:
  application:
    name: MI-TOOL-SERVER
  cloud:
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
    nacos:
      server-addr: 39.97.76.127
      discovery:
        group: MI-GROUP
  redis:
    cluster:
      nodes:
        - 81.70.197.232:6391
        - 81.70.197.232:6392
        - 81.70.197.232:6393
        - 81.70.197.232:6394
        - 81.70.197.232:6395
        - 81.70.197.232:6396
  mail:
    host: smtp.qq.com
    password:
    port: 465
    username:
    protocol: smtps
  datasource:
    url: jdbc:mysql://127.0.0.1:10054/mi-community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
sms:
  config:
    sign-name:
    template-code:

rocketmq:
  name-server: 8.129.40.60:9876
  producer:
    group: MI-TOOL-GROUP

oss:
  config:
    bucket:
      avatar: weixiaohan-avatar
      post: weixiaohan-post