server:
  port: 1004
  tomcat:
    max-swallow-size: 100MB
spring:
  application:
    name: MI-TOOL-SERVER
  cloud:
    alicloud:
      access-key: LTAI4G6dh6WpfJXQXgHGzGi6
      secret-key: XmXumSWCQawqxiXWhEmcVJF3aNil2g
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
    nacos:
      server-addr: 39.97.76.127
      discovery:
        group: MI-GROUP
  redis:
    cluster:
      nodes:
        - 81.70.197.232:6391
        - 81.70.197.232:6392
        - 81.70.197.232:6393
        - 81.70.197.232:6394
        - 81.70.197.232:6395
        - 81.70.197.232:6396
    lettuce:
      shutdown-timeout: 3000ms
  mail:
    host: smtp.qq.com
    password: qyznrzfmcbfsbfhc
    port: 465
    username: zhangfangtao25@qq.com
    protocol: smtps
  datasource:
    url: jdbc:mysql://cdb-bopgeseg.cd.tencentcdb.com:10054/mi-community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: weihanhan1005
    hikari:
      max-lifetime: 600000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
sms:
  config:
    sign-name: ABC商城
    template-code: SMS_207105138

rocketmq:
  name-server: 8.129.40.60:9876
  producer:
    group: MI-TOOL-GROUP

oss:
  config:
    bucket:
      avatar: weixiaohan-avatar
      post: weixiaohan-post

