server:
  port: 7071
spring:
  application:
    name: MI-AUTH-SERVER
  datasource:
    url: jdbc:mysql://cdb-bopgeseg.cd.tencentcdb.com:10054/authorization_server
    username: root
    password: weihanhan1005
    hikari:
      max-lifetime: 300000
  redis:
    cluster:
      nodes:
        - 81.70.197.232:6391
        - 81.70.197.232:6392
        - 81.70.197.232:6393
        - 81.70.197.232:6394
        - 81.70.197.232:6395
        - 81.70.197.232:6396
  cloud:
    nacos:
      server-addr: 39.97.76.127
      discovery:
        group: MI-GROUP
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: false
    response:
      enabled: false
auth:
  social:
    type:
      gitee:
        client-id: 63001e333c6dac343ac5c0e86c244f704ca732b9a7383537d119d9b00724f173
        client-secret: 08751c6b620ccff59513d43aeaa57f996db2f381c133e2f4268bd62378b1cb8e
        redirect-uri: http://127.0.0.1:7071/third/callback/gitee
rocketmq:
  name-server: 8.129.40.60:9876
  producer:
    group: USERINFO-GROUP
