server:
  port: 7071
spring:
  application:
    name: MI-AUTH-SERVER
  datasource:
    url: jdbc:mysql://127.0.0.1:10054/authorization_server
    username: root
    password:
    hikari:
      max-lifetime: 300000
  redis:
    cluster:
      nodes:
        - 81.70.197.232:6391
        - 81.70.197.232:6392
        - 81.70.197.232:6393
        - 81.70.197.232:6394
        - 81.70.197.232:6395
        - 81.70.197.232:6396
  cloud:
    nacos:
      server-addr: 47.115.130.177
      discovery:
        group: MI-DEV-GROUP
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: false
    response:
      enabled: false
auth:
  social:
    type:
      gitee:
        client-id:
        client-secret:
        redirect-uri: http://127.0.0.1:7071/third/callback/gitee
rocketmq:
  name-server: 8.129.40.60:9876
  producer:
    group: USERINFO-DEV-GROUP
