server:
  port: 1006
spring:
  datasource:
    url: jdbc:mysql://cdb-bopgeseg.cd.tencentcdb.com:10054/mi-community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: weihanhan1005
    hikari:
      max-lifetime: 250000
  redis:
    cluster:
      nodes:
        - 81.70.197.232:6391
        - 81.70.197.232:6392
        - 81.70.197.232:6393
        - 81.70.197.232:6394
        - 81.70.197.232:6395
        - 81.70.197.232:6396
  application:
    name: MI-USER-SERVER
  cloud:
    nacos:
      server-addr: 39.97.76.127:8848
      discovery:
        group: MI-GROUP
rocketmq:
  name-server: 8.129.40.60:9876
  producer:
    group: MI-USER-PRODUCER
