server:
  port: 1006
  servlet:
    context-path: /mi-user
spring:
  datasource:
    url: jdbc:mysql://cdb-bopgeseg.cd.tencentcdb.com:10054/mi-community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: weihanhan1005
  redis:
    host: 8.129.40.60
  application:
    name: MI-USER-SERVER
  cloud:
    nacos:
      server-addr: 39.97.76.127:8848
      discovery:
        group: MI-GROUP
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: dd/MM/yyyy
logging:
  file:
    name: mi-post
    path: E:\code\logfile
rocketmq:
  name-server: 8.129.40.60:9876
  producer:
    group: MI-TEST-PRODUCER
